#!/bin/bash

NEW_USERS=('1234' '5678' '9123')
NEW_GROUPS=('4567' '8912' '3456')

MY_UID=8773
PRINCIPAL_GID=1530

USER="-L --capath /etc/grid-security/certificates  --cert /tmp/x509up_u`id -u` --cacert /tmp/x509up_u`id -u` --key  /tmp/x509up_u`id -u` "
ADMIN="-u arossi#admin:antioca $USER"

echo "Current users"
curl $USER -X GET "https://fndcatemp2.fnal.gov:3880/api/v1/quota/user" -H "accept: application/json"
echo ""
echo ""
echo "Current groups"
curl $USER -X GET "https://fndcatemp2.fnal.gov:3880/api/v1/quota/group" -H "accept: application/json"  
echo ""
echo "----------------------------------------------------------------------------------------------------"

echo "Add empty user quota for self"
curl $USER -X POST "https://fndcatemp2.fnal.gov:3880/api/v1/quota/user/$MY_UID" -H "accept: application/json" -H "content-type: application/json" -d "{}"
echo ""
curl $USER -X GET "https://fndcatemp2.fnal.gov:3880/api/v1/quota/user" -H "accept: application/json"  
echo ""
echo ""
echo "Add empty group quota for self"
curl $USER -X POST "https://fndcatemp2.fnal.gov:3880/api/v1/quota/group/$PRINCIPAL_GID" -H "accept: application/json" -H "content-type: application/json" -d "{}"
echo ""
curl $USER -X GET "https://fndcatemp2.fnal.gov:3880/api/v1/quota/group" -H "accept: application/json" 
echo ""
echo "----------------------------------------------------------------------------------------------------"

echo "Add empty user quota for arbitrary user, but not as admin"
curl $USER -X POST "https://fndcatemp2.fnal.gov:3880/api/v1/quota/user/${NEW_USERS[0]}" -H "accept: application/json" -H "content-type: application/json" -d "{}"
echo ""
echo ""
echo "Add empty group quota for arbitrary group, but not as admin"
curl $USER -X POST "https://fndcatemp2.fnal.gov:3880/api/v1/quota/group/${NEW_GROUPS[0]}" -H "accept: application/json" -H "content-type: application/json" -d "{}"
echo ""
echo "----------------------------------------------------------------------------------------------------"

echo "Add empty user quota for self, as admin"
curl $ADMIN -X POST "https://fndcatemp2.fnal.gov:3880/api/v1/quota/user/$MY_UID" -H "accept: application/json" -H "content-type: application/json" -d "{}"
echo ""
curl $USER -X GET "https://fndcatemp2.fnal.gov:3880/api/v1/quota/user" -H "accept: application/json"
echo ""
echo ""
echo "Add empty group quota for self, as admin"
curl $ADMIN -X POST "https://fndcatemp2.fnal.gov:3880/api/v1/quota/group/$PRINCIPAL_GID" -H "accept: application/json" -H "content-type: application/json" -d "{}"
echo ""
curl $USER -X GET "https://fndcatemp2.fnal.gov:3880/api/v1/quota/group" -H "accept: application/json"
echo ""
echo "----------------------------------------------------------------------------------------------------"

echo "Add empty user quota for arbitrary user, as admin"
curl $ADMIN -X POST "https://fndcatemp2.fnal.gov:3880/api/v1/quota/user/${NEW_USERS[0]}" -H "accept: application/json" -H "content-type: application/json" -d "{}"
echo ""
curl $USER -X GET "https://fndcatemp2.fnal.gov:3880/api/v1/quota/user" -H "accept: application/json"
echo ""
echo ""
echo "Add empty group quota for arbitrary group, as admin"
curl $ADMIN -X POST "https://fndcatemp2.fnal.gov:3880/api/v1/quota/group/${NEW_GROUPS[0]}" -H "accept: application/json" -H "content-type: application/json" -d "{}"
echo ""
curl $USER -X GET "https://fndcatemp2.fnal.gov:3880/api/v1/quota/group" -H "accept: application/json"
echo ""
echo "----------------------------------------------------------------------------------------------------"

echo "Add non-empty user quota for arbitrary user (as admin)"
curl $ADMIN -X POST "https://fndcatemp2.fnal.gov:3880/api/v1/quota/user/${NEW_USERS[1]}" -H "accept: application/json" -H "content-type: application/json" -d "{'custodialLimit':'10 TiB','replicaLimit':'1 TiB'}"
echo ""
curl $USER -X GET "https://fndcatemp2.fnal.gov:3880/api/v1/quota/user" -H "accept: application/json"
echo ""
echo ""
echo "Add non-empty group quota for arbitrary group (as admin)"
curl $ADMIN -X POST "https://fndcatemp2.fnal.gov:3880/api/v1/quota/group/${NEW_GROUPS[1]}" -H "accept: application/json" -H "content-type: application/json" -d "{'custodialLimit':'10 TiB','replicaLimit':'1 TiB'}"
echo ""
curl $USER -X GET "https://fndcatemp2.fnal.gov:3880/api/v1/quota/group" -H "accept: application/json"
echo ""
echo "----------------------------------------------------------------------------------------------------"

echo "Update user quota as self"
curl $USER -X PATCH "https://fndcatemp2.fnal.gov:3880/api/v1/quota/user/$MY_UID" -H "accept: application/json" -H "content-type: application/json" -d "{'custodialLimit':'10 TiB','replicaLimit':'1 TiB'}"
echo ""
echo ""
echo "Update group quota as self"
curl $USER -X PATCH "https://fndcatemp2.fnal.gov:3880/api/v1/quota/group/$PRINCIPAL_GID" -H "accept: application/json" -H "content-type: application/json" -d "{'custodialLimit':'10 TiB','replicaLimit':'1 TiB'}"
echo ""
echo "----------------------------------------------------------------------------------------------------"

echo "Update user quota by adding values (as admin)"
curl $ADMIN -X PATCH "https://fndcatemp2.fnal.gov:3880/api/v1/quota/user/$MY_UID" -H "accept: application/json" -H "content-type: application/json" -d "{'custodialLimit':'10 TiB','replicaLimit':'1 TiB'}"
echo ""
curl $USER -X GET "https://fndcatemp2.fnal.gov:3880/api/v1/quota/user" -H "accept: application/json"
echo ""
echo ""
echo "Update group quota by adding values (as admin)"
curl $ADMIN -X PATCH "https://fndcatemp2.fnal.gov:3880/api/v1/quota/group/$PRINCIPAL_GID" -H "accept: application/json" -H "content-type: application/json" -d "{'custodialLimit':'10 TiB','replicaLimit':'1 TiB'}"
echo ""
curl $USER -X GET "https://fndcatemp2.fnal.gov:3880/api/v1/quota/group" -H "accept: application/json"
echo ""
echo "----------------------------------------------------------------------------------------------------"

echo "Update user quota by modifying a value (as admin)"
curl $ADMIN -X PATCH "https://fndcatemp2.fnal.gov:3880/api/v1/quota/user/$MY_UID" -H "accept: application/json" -H "content-type: application/json" -d "{'custodialLimit':'2 TiB'}"
echo ""
curl $USER -X GET "https://fndcatemp2.fnal.gov:3880/api/v1/quota/user" -H "accept: application/json"
echo ""
echo ""
echo "Update group quota by modifying a value (as admin)"
curl $ADMIN -X PATCH "https://fndcatemp2.fnal.gov:3880/api/v1/quota/group/$PRINCIPAL_GID" -H "accept: application/json" -H "content-type: application/json" -d "{'custodialLimit':'2 TiB'}"
echo ""
curl $USER -X GET "https://fndcatemp2.fnal.gov:3880/api/v1/quota/group" -H "accept: application/json"
echo ""
echo "----------------------------------------------------------------------------------------------------"

echo "Update user quota by removing a value (as admin)"
curl $ADMIN -X PATCH "https://fndcatemp2.fnal.gov:3880/api/v1/quota/user/$MY_UID" -H "accept: application/json" -H "content-type: application/json" -d "{'custodialLimit':'NONE'}"
echo ""
curl $USER -X GET "https://fndcatemp2.fnal.gov:3880/api/v1/quota/user" -H "accept: application/json"
echo ""
echo ""
echo "Update group quota by removing a value (as admin)"
curl $ADMIN -X PATCH "https://fndcatemp2.fnal.gov:3880/api/v1/quota/group/$PRINCIPAL_GID" -H "accept: application/json" -H "content-type: application/json" -d "{'custodialLimit':'NONE'}"
echo ""
curl $USER -X GET "https://fndcatemp2.fnal.gov:3880/api/v1/quota/group" -H "accept: application/json"
echo ""
echo "----------------------------------------------------------------------------------------------------"

echo "Try to add user quota for existing quota (as admin)"
curl $ADMIN -X POST "https://fndcatemp2.fnal.gov:3880/api/v1/quota/user/$MY_UID" -H "accept: application/json" -H "content-type: application/json" -d "{}" 
echo ""
echo ""
echo "Try to add group quota for existing quota (as admin)" 
curl $ADMIN -X POST "https://fndcatemp2.fnal.gov:3880/api/v1/quota/group/$PRINCIPAL_GID" -H "accept: application/json" -H "content-type: application/json" -d "{}"
echo ""
echo "----------------------------------------------------------------------------------------------------"

echo "Try to update non-existent user quota (as admin)"
curl $ADMIN -X PATCH "https://fndcatemp2.fnal.gov:3880/api/v1/quota/user/${NEW_USERS[2]}" -H "accept: application/json" -H "content-type: application/json" -d "{'custodialLimit':'10 TiB','replicaLimit':'1 TiB'}"
echo ""
echo ""
echo "Try to update non-existent group quota (as admin)"
curl $ADMIN -X PATCH "https://fndcatemp2.fnal.gov:3880/api/v1/quota/group/${NEW_GROUPS[2]}" -H "accept: application/json" -H "content-type: application/json" -d "{'custodialLimit':'10 TiB','replicaLimit':'1 TiB'}"
echo ""
echo "----------------------------------------------------------------------------------------------------"

echo "List quotas for user with user=true"
curl $USER -X GET "https://fndcatemp2.fnal.gov:3880/api/v1/quota/user?user=true" -H "accept: application/json"
echo ""
echo ""
echo "List quotas for group with group=true"
curl $USER -X GET "https://fndcatemp2.fnal.gov:3880/api/v1/quota/group?user=true" -H "accept: application/json"
echo ""
echo "----------------------------------------------------------------------------------------------------"

echo "Get all user quotas as anonymous user"
curl -k -X GET "https://fndcatemp2.fnal.gov:3880/api/v1/quota/user" -H "accept: application/json"
echo ""
echo ""
echo "Get all group quotas as anonymous user"
curl -k  -X GET "https://fndcatemp2.fnal.gov:3880/api/v1/quota/group" -H "accept: application/json"
echo ""
echo "----------------------------------------------------------------------------------------------------"

echo "Get user quota as anonymous user"
curl -k  -X GET "https://fndcatemp2.fnal.gov:3880/api/v1/quota/user/${NEW_USERS[0]}" -H "accept: application/json"
echo ""
echo ""
echo "Get group quota as anonymous user"
curl -k  -X GET "https://fndcatemp2.fnal.gov:3880/api/v1/quota/group/${NEW_GROUPS[0]}" -H "accept: application/json"
echo ""
echo "----------------------------------------------------------------------------------------------------"

echo "Get quota for user (not self)"
curl $USER -X GET "https://fndcatemp2.fnal.gov:3880/api/v1/quota/user/${NEW_USERS[0]}" -H "accept: application/json"
echo ""
echo ""
echo "Get quota for (arbitrary) group"
curl $USER -X GET "https://fndcatemp2.fnal.gov:3880/api/v1/quota/group/${NEW_GROUPS[0]}" -H "accept: application/json"
echo ""
echo "----------------------------------------------------------------------------------------------------"

echo "Get quota for non-existent user"
curl $USER -X GET "https://fndcatemp2.fnal.gov:3880/api/v1/quota/user/${NEW_USERS[2]}" -H "accept: application/json"
echo ""
echo ""
echo "Get quota for non-existent group"
curl $USER -X GET "https://fndcatemp2.fnal.gov:3880/api/v1/quota/group/${NEW_GROUPS[2]}" -H "accept: application/json"
echo ""
echo "----------------------------------------------------------------------------------------------------"

echo "Remove own user quota (as user)"
curl $USER -X DELETE "https://fndcatemp2.fnal.gov:3880/api/v1/quota/user/$MY_UID" -H "accept: application/json"
echo ""
echo ""
echo "Remove own group quota (as user)"
curl $USER -X DELETE "https://fndcatemp2.fnal.gov:3880/api/v1/quota/group/$PRINCIPAL_GID" -H "accept: application/json"
echo ""
echo "----------------------------------------------------------------------------------------------------"

echo "Remove arbitrary user quota (as user)"
curl $USER -X DELETE "https://fndcatemp2.fnal.gov:3880/api/v1/quota/user/${NEW_USERS[0]}" -H "accept: application/json"
echo ""
echo ""
echo "Remove arbitrary group quota (as user)"
curl $USER -X DELETE "https://fndcatemp2.fnal.gov:3880/api/v1/quota/group/${NEW_GROUPS[0]}" -H "accept: application/json"
echo ""
echo "----------------------------------------------------------------------------------------------------"

echo "Remove user quota (as admin)"
curl $ADMIN -X DELETE "https://fndcatemp2.fnal.gov:3880/api/v1/quota/user/$MY_UID" -H "accept: application/json"
echo ""
curl $USER -X GET "https://fndcatemp2.fnal.gov:3880/api/v1/quota/user"
echo ""
echo ""
echo "Remove group quota (as admin)"
curl $ADMIN -X DELETE "https://fndcatemp2.fnal.gov:3880/api/v1/quota/group/$PRINCIPAL_GID" -H "accept: application/json"
echo ""
curl $USER -X GET "https://fndcatemp2.fnal.gov:3880/api/v1/quota/group"
echo ""
echo "----------------------------------------------------------------------------------------------------"

echo "Remove arbitrary user quotas (as admin)"
curl $ADMIN -X DELETE "https://fndcatemp2.fnal.gov:3880/api/v1/quota/user/${NEW_USERS[0]}" -H "accept: application/json"
echo ""
curl $ADMIN -X DELETE "https://fndcatemp2.fnal.gov:3880/api/v1/quota/user/${NEW_USERS[1]}" -H "accept: application/json"
echo ""
curl $USER -X GET "https://fndcatemp2.fnal.gov:3880/api/v1/quota/user"
echo ""
echo ""
echo "Remove arbitrary group quotas (as admin)"
curl $ADMIN -X DELETE "https://fndcatemp2.fnal.gov:3880/api/v1/quota/group/${NEW_GROUPS[0]}" -H "accept: application/json"
echo ""
curl $ADMIN -X DELETE "https://fndcatemp2.fnal.gov:3880/api/v1/quota/group/${NEW_GROUPS[1]}" -H "accept: application/json"
echo ""
curl $USER -X GET "https://fndcatemp2.fnal.gov:3880/api/v1/quota/group"
echo ""
echo "----------------------------------------------------------------------------------------------------"

echo "Remove non-existent user quota (as admin)"
curl $ADMIN -X DELETE "https://fndcatemp2.fnal.gov:3880/api/v1/quota/user/${NEW_USERS[2]}" -H "accept: application/json"
echo ""
echo ""
echo "Remove non-existent group quota (as admin)"
curl $ADMIN -X DELETE "https://fndcatemp2.fnal.gov:3880/api/v1/quota/group/${NEW_GROUPS[2]}" -H "accept: application/json"
echo ""
echo "----------------------------------------------------------------------------------------------------"

echo "Confirming no quotas left:"
curl $USER -X GET "https://fndcatemp2.fnal.gov:3880/api/v1/quota/user"
echo ""
curl $USER -X GET "https://fndcatemp2.fnal.gov:3880/api/v1/quota/group"
echo ""